namespace QuanLyNhaTre.QuanLyHocTap
{
    partial class QuanLyDiemDanh
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.textBox2 = new System.Windows.Forms.TextBox();
            this.checkedListBox1 = new System.Windows.Forms.CheckedListBox();
            this.label3 = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.button1 = new System.Windows.Forms.Button();
            this.button2 = new System.Windows.Forms.Button();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.label4 = new System.Windows.Forms.Label();
            this.textBox3 = new System.Windows.Forms.TextBox();
            this.button3 = new System.Windows.Forms.Button();
            this.label5 = new System.Windows.Forms.Label();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(14, 30);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(55, 13);
            this.label1.TabIndex = 0;
            this.label1.Text = "Giáo viên:";
            // 
            // textBox1
            // 
            this.textBox1.Location = new System.Drawing.Point(75, 30);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new System.Drawing.Size(100, 20);
            this.textBox1.TabIndex = 1;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(191, 30);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(39, 13);
            this.label2.TabIndex = 0;
            this.label2.Text = "Mã lớp";
            // 
            // textBox2
            // 
            this.textBox2.Location = new System.Drawing.Point(235, 30);
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new System.Drawing.Size(100, 20);
            this.textBox2.TabIndex = 1;
            // 
            // checkedListBox1
            // 
            this.checkedListBox1.BackColor = System.Drawing.SystemColors.Info;
            this.checkedListBox1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.checkedListBox1.FormattingEnabled = true;
            this.checkedListBox1.Items.AddRange(new object[] {
            "TT",
            "\t",
            "Mã số sinh viên",
            "\t",
            "Họ tên sinh viên",
            "\t",
            "Lớp cũ",
            "\t",
            "Ngành được xếp",
            "\t",
            "Lớp",
            "1",
            "\t",
            "20112736",
            "\t",
            "Vũ Minh An",
            "\t",
            "BK3.13 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "2",
            "\t",
            "20112769",
            "\t",
            "Phạm Tuấn Anh",
            "\t",
            "BK3.02 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "3",
            "\t",
            "20112774",
            "\t",
            "Vũ Đức Anh",
            "\t",
            "BK3.17 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "4",
            "\t",
            "20112794",
            "\t",
            "Nguyễn Hữu Chí Công",
            "\t",
            "BK3.02 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "5",
            "\t",
            "20112804",
            "\t",
            "Nguyễn Văn Cường",
            "\t",
            "BK3.09 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "6",
            "\t",
            "20112805",
            "\t",
            "Vũ Thị Phương Châm",
            "\t",
            "BK3.13 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "7",
            "\t",
            "20112828",
            "\t",
            "Ngô Việt Dũng",
            "\t",
            "BK3.18 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "8",
            "\t",
            "20112829",
            "\t",
            "Nguyễn Anh Dũng",
            "\t",
            "BK3.09 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "9",
            "\t",
            "20112836",
            "\t",
            "Vũ Quang Dũng",
            "\t",
            "BK3.17 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "10",
            "\t",
            "20112852",
            "\t",
            "Nguyễn Thị Dung",
            "\t",
            "BK3.12 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "11",
            "\t",
            "20112864",
            "\t",
            "Đoàn Anh Đào",
            "\t",
            "BK3.14 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "12",
            "\t",
            "20112902",
            "\t",
            "Nguyễn Thành Đoàn",
            "\t",
            "BK3.08 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "13",
            "\t",
            "20112915",
            "\t",
            "Nguyễn Quang Hà",
            "\t",
            "BK3.12 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "14",
            "\t",
            "20112918",
            "\t",
            "Trần Thị Hưng Hà",
            "\t",
            "BK3.11 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "15",
            "\t",
            "20112922",
            "\t",
            "Đoàn Ngọc Hải",
            "\t",
            "BK3.05 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "16",
            "\t",
            "20112940",
            "\t",
            "Vũ Đức Hồ",
            "\t",
            "BK3.03 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "17",
            "\t",
            "20112945",
            "\t",
            "Lê Khánh Hùng",
            "\t",
            "BK3.18 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "18",
            "\t",
            "20112951",
            "\t",
            "Nguyễn Văn Hùng",
            "\t",
            "BK3.10 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "19",
            "\t",
            "20112970",
            "\t",
            "Nguyễn Phúc Hưng",
            "\t",
            "BK3.14 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "20",
            "\t",
            "20112992",
            "\t",
            "Nguyễn Trung Hiếu",
            "\t",
            "BK3.02 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "21",
            "\t",
            "20112996",
            "\t",
            "Thân Trung Hiếu",
            "\t",
            "BK3.09 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "22",
            "\t",
            "20113014",
            "\t",
            "Đặng Xuân Hoàng",
            "\t",
            "BK3.09 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "23",
            "\t",
            "20113028",
            "\t",
            "Đinh Công Huy",
            "\t",
            "BK3.04 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "24",
            "\t",
            "20113035",
            "\t",
            "Trần Quang Huy",
            "\t",
            "BK3.16 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "25",
            "\t",
            "20113051",
            "\t",
            "Nguyễn Trọng Khoát",
            "\t",
            "BK3.02 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "26",
            "\t",
            "20113055",
            "\t",
            "Đỗ Thị Kim Khuyên",
            "\t",
            "BK3.04 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "27",
            "\t",
            "20113075",
            "\t",
            "Vũ Văn Lượng",
            "\t",
            "BK3.05 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "28",
            "\t",
            "20113092",
            "\t",
            "Mai Khánh Linh",
            "\t",
            "BK3.10 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "29",
            "\t",
            "20113102",
            "\t",
            "Nguyễn Vũ Tùng Linh",
            "\t",
            "BK3.10 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "30",
            "\t",
            "20113103",
            "\t",
            "Phạm Hữu Linh",
            "\t",
            "BK3.11 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "31",
            "\t",
            "20113112",
            "\t",
            "Ngô Văn Long",
            "\t",
            "BK3.16 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "32",
            "\t",
            "20113122",
            "\t",
            "Ngô Tuấn Mạnh",
            "\t",
            "BK3.01 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "33",
            "\t",
            "20113161",
            "\t",
            "Lê Phương Nam",
            "\t",
            "BK3.05 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "34",
            "\t",
            "20113166",
            "\t",
            "Vũ Tuyết Ngân",
            "\t",
            "BK3.18 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "35",
            "\t",
            "20113192",
            "\t",
            "Phạm Chí Nhu",
            "\t",
            "BK3.13 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "36",
            "\t",
            "20113201",
            "\t",
            "Nguyễn Hải Ninh",
            "\t",
            "BK3.01 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "37",
            "\t",
            "20113210",
            "\t",
            "Nguyễn Thị Bích Phương",
            "\t",
            "BK3.18 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "38",
            "\t",
            "20113212",
            "\t",
            "Nguyễn Việt Phương",
            "\t",
            "BK3.05 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "39",
            "\t",
            "20113221",
            "\t",
            "Lương Tuấn Phong",
            "\t",
            "BK3.15 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "40",
            "\t",
            "20113239",
            "\t",
            "Vương Văn Quý",
            "\t",
            "BK3.16 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "41",
            "\t",
            "20113259",
            "\t",
            "Lê Hoàng Sơn",
            "\t",
            "BK3.14 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "42",
            "\t",
            "20113267",
            "\t",
            "Trần Anh Sơn",
            "\t",
            "BK3.02 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "43",
            "\t",
            "20113299",
            "\t",
            "Nguyễn Mạnh Tùng",
            "\t",
            "BK3.08 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "44",
            "\t",
            "20113302",
            "\t",
            "Nguyễn Thanh Tùng",
            "\t",
            "BK3.11 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "45",
            "\t",
            "20113313",
            "\t",
            "Nguyễn Thị Tươi",
            "\t",
            "BK3.15 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "46",
            "\t",
            "20113318",
            "\t",
            "Phạm Công Thành",
            "\t",
            "BK3.03 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "47",
            "\t",
            "20113320",
            "\t",
            "Trần Tiến Thành",
            "\t",
            "BK3.15 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "48",
            "\t",
            "20113354",
            "\t",
            "Lê Đức Thọ",
            "\t",
            "BK3.05 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "49",
            "\t",
            "20113375",
            "\t",
            "Vũ Đức Thao",
            "\t",
            "BK3.05 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "50",
            "\t",
            "20113407",
            "\t",
            "Phạm Quang Trường",
            "\t",
            "BK3.05 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "51",
            "\t",
            "20113412",
            "\t",
            "Đặng Thu Trang",
            "\t",
            "BK3.13 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "52",
            "\t",
            "20113420",
            "\t",
            "Nguyễn Thị Thu Trang",
            "\t",
            "BK3.11 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "53",
            "\t",
            "20113422",
            "\t",
            "Phạm Thị Thu Trang",
            "\t",
            "BK3.07 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "54",
            "\t",
            "20113437",
            "\t",
            "Trần Đức Trung",
            "\t",
            "BK3.02 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "55",
            "\t",
            "20113479",
            "\t",
            "Nguyễn Đức Việt",
            "\t",
            "BK3.12 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "56",
            "\t",
            "20113488",
            "\t",
            "Lê Viết Vinh",
            "\t",
            "BK3.16 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "57",
            "\t",
            "20113495",
            "\t",
            "Đoàn Thị Yến",
            "\t",
            "BK3.13 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "58",
            "\t",
            "20113550",
            "\t",
            "Phan Trọng Nghĩa",
            "\t",
            "BK3.10 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "59",
            "\t",
            "20113580",
            "\t",
            "Trần Thị Thúy",
            "\t",
            "BK3.12 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "60",
            "\t",
            "20113741",
            "\t",
            "Vũ Duy Linh",
            "\t",
            "BK3.01 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "61",
            "\t",
            "20110618",
            "\t",
            "Phạm Hồng Quân",
            "\t",
            "BK1.19 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "62",
            "\t",
            "20112733",
            "\t",
            "Nguyễn Năng An",
            "\t",
            "BK3.06 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "63",
            "\t",
            "20112753",
            "\t",
            "Nguyễn Phương Anh",
            "\t",
            "BK3.03 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "64",
            "\t",
            "20112786",
            "\t",
            "Phan Văn Bắc",
            "\t",
            "BK3.14 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "65",
            "\t",
            "20112793",
            "\t",
            "Lê Văn Công",
            "\t",
            "BK3.10 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "66",
            "\t",
            "20112797",
            "\t",
            "Phạm Việt Biên Cương",
            "\t",
            "BK3.04 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "67",
            "\t",
            "20112825",
            "\t",
            "Đào Hữu Dũng",
            "\t",
            "BK3.07 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "68",
            "\t",
            "20112838",
            "\t",
            "Hoàng Minh Dương",
            "\t",
            "BK3.10 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "69",
            "\t",
            "20112857",
            "\t",
            "Nguyễn Anh Duy",
            "\t",
            "BK3.14 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "70",
            "\t",
            "20112861",
            "\t",
            "Trần Thế Duy",
            "\t",
            "BK3.03 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "71",
            "\t",
            "20112881",
            "\t",
            "Vương Đức Đạt",
            "\t",
            "BK3.13 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "72",
            "\t",
            "20112892",
            "\t",
            "Lê Anh Đức",
            "\t",
            "BK3.03 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "73",
            "\t",
            "20112896",
            "\t",
            "Nguyễn Văn Đức",
            "\t",
            "BK3.13 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "74",
            "\t",
            "20112912",
            "\t",
            "Đỗ Thị Thu Hà",
            "\t",
            "BK3.04 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "75",
            "\t",
            "20112913",
            "\t",
            "Đinh Thị Hà",
            "\t",
            "BK3.11 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "76",
            "\t",
            "20112968",
            "\t",
            "Lê Hoàng Hưng",
            "\t",
            "BK3.05 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "77",
            "\t",
            "20112982",
            "\t",
            "Nguyễn Thị Hiền",
            "\t",
            "BK3.07 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "78",
            "\t",
            "20112984",
            "\t",
            "Nguyễn Thị Thu Hiền",
            "\t",
            "BK3.14 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "79",
            "\t",
            "20113039",
            "\t",
            "Trần Thị Huyền",
            "\t",
            "BK3.12 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "80",
            "\t",
            "20113049",
            "\t",
            "Phạm Văn Khương",
            "\t",
            "BK3.12 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "81",
            "\t",
            "20113065",
            "\t",
            "Nguyễn Viết Lãm",
            "\t",
            "BK3.09 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "82",
            "\t",
            "20113104",
            "\t",
            "Trần Vũ Khánh Linh",
            "\t",
            "BK3.04 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "83",
            "\t",
            "20113132",
            "\t",
            "Cao Thị Tú Mai",
            "\t",
            "BK3.13 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "84",
            "\t",
            "20113144",
            "\t",
            "Lâm Đức Minh",
            "\t",
            "BK3.07 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "85",
            "\t",
            "20113156",
            "\t",
            "Vũ Đình Năm",
            "\t",
            "BK3.02 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "86",
            "\t",
            "20113165",
            "\t",
            "Trần Kim Ngân",
            "\t",
            "BK3.08 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "87",
            "\t",
            "20113170",
            "\t",
            "Trần Thị Ngọc",
            "\t",
            "BK3.14 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "88",
            "\t",
            "20113180",
            "\t",
            "Nguyễn Văn Nghĩa",
            "\t",
            "BK3.07 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "89",
            "\t",
            "20113191",
            "\t",
            "Nguyễn Thị Hương Nho",
            "\t",
            "BK3.11 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "90",
            "\t",
            "20113193",
            "\t",
            "Đào Thị Hồng Nhung",
            "\t",
            "BK3.09 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "91",
            "\t",
            "20113195",
            "\t",
            "Nguyễn Hồng Nhung",
            "\t",
            "BK3.05 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "92",
            "\t",
            "20113208",
            "\t",
            "Nguyễn Thị Phương",
            "\t",
            "BK3.18 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "93",
            "\t",
            "20113225",
            "\t",
            "Cao Thế Quân",
            "\t",
            "BK3.08 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "94",
            "\t",
            "20113238",
            "\t",
            "Trần Võ Quý",
            "\t",
            "BK3.10 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "95",
            "\t",
            "20113240",
            "\t",
            "Mạc Duy Quang",
            "\t",
            "BK3.14 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "96",
            "\t",
            "20113241",
            "\t",
            "Nguyễn Đắc Quang",
            "\t",
            "BK3.12 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "97",
            "\t",
            "20113250",
            "\t",
            "Phùng Hoàng Quyền",
            "\t",
            "BK3.04 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "98",
            "\t",
            "20113257",
            "\t",
            "Đặng Thanh Sơn",
            "\t",
            "BK3.03 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "99",
            "\t",
            "20113279",
            "\t",
            "Nguyễn Thị Thanh Tâm",
            "\t",
            "BK3.02 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1",
            "100",
            "\t",
            "20113330",
            "\t",
            "Nguyễn Thị Phương Thảo",
            "\t",
            "BK3.05 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\\",
            "20113341",
            "\t",
            "Hoàng Minh Thắng",
            "\t",
            "BK3.06 K56",
            "\t",
            "Kỹ thuật môi trường 2011",
            "\t",
            "1"});
            this.checkedListBox1.Location = new System.Drawing.Point(34, 158);
            this.checkedListBox1.Name = "checkedListBox1";
            this.checkedListBox1.Size = new System.Drawing.Size(526, 277);
            this.checkedListBox1.TabIndex = 2;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 20F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(245, 18);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(254, 31);
            this.label3.TabIndex = 0;
            this.label3.Text = "Điểm danh đầu buổi";
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.button2);
            this.groupBox1.Controls.Add(this.button3);
            this.groupBox1.Controls.Add(this.button1);
            this.groupBox1.Location = new System.Drawing.Point(587, 29);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(150, 106);
            this.groupBox1.TabIndex = 3;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Chức năng";
            // 
            // button1
            // 
            this.button1.Location = new System.Drawing.Point(21, 19);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(110, 23);
            this.button1.TabIndex = 0;
            this.button1.Text = "Đóng sổ";
            this.button1.UseVisualStyleBackColor = true;
            // 
            // button2
            // 
            this.button2.Location = new System.Drawing.Point(21, 77);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(110, 23);
            this.button2.TabIndex = 0;
            this.button2.Text = "Đóng";
            this.button2.UseVisualStyleBackColor = true;
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.textBox1);
            this.groupBox2.Controls.Add(this.label1);
            this.groupBox2.Controls.Add(this.textBox3);
            this.groupBox2.Controls.Add(this.label4);
            this.groupBox2.Controls.Add(this.textBox2);
            this.groupBox2.Controls.Add(this.label2);
            this.groupBox2.Location = new System.Drawing.Point(34, 52);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(526, 63);
            this.groupBox2.TabIndex = 4;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Thông tin";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(351, 30);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(35, 13);
            this.label4.TabIndex = 0;
            this.label4.Text = "Ngày:";
            // 
            // textBox3
            // 
            this.textBox3.Location = new System.Drawing.Point(396, 30);
            this.textBox3.Name = "textBox3";
            this.textBox3.Size = new System.Drawing.Size(124, 20);
            this.textBox3.TabIndex = 1;
            // 
            // button3
            // 
            this.button3.Location = new System.Drawing.Point(21, 48);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(110, 23);
            this.button3.TabIndex = 0;
            this.button3.Text = "Cập nhật";
            this.button3.UseVisualStyleBackColor = true;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(48, 133);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(147, 13);
            this.label5.TabIndex = 0;
            this.label5.Text = "Danh sách các bé đã đi học:";
            // 
            // QuanLyDiemDanh
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(751, 447);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.checkedListBox1);
            this.Controls.Add(this.label3);
            this.Name = "QuanLyDiemDanh";
            this.Text = "QuanLyDiemDanh";
            this.groupBox1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox textBox2;
        private System.Windows.Forms.CheckedListBox checkedListBox1;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.Button button3;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.TextBox textBox3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
    }
}