
insert into HOSOTREEM values ('Nguyễn Văn A','Nguyễn Thị B','Nguyễn Văn D','d@gmail.com','0978828176','Xóm nhà lá, Phường 10, Quận 11, Tp HCM')
insert into HOSOTREEM values ('Nguyễn Văn Tý','Nguyễn Thị Tỵ','Nguyễn Văn Ty','ty@gmail.com','0973112176','Xóm nhà Tranh, Phường 10, Quận 11, Tp HCM')
insert into HOSOTREEM values ('Nguyễn Văn Nam','Nguyễn Thị Nữ','Nguyễn Văn Bê','be@gmail.com','0978348176','Xóm nhà lá, Phường 10, Quận 11, Tp HCM')
insert into HOSOTREEM values ('Nguyễn Văn Anh','Nguyễn Thị Ân','Nguyễn Văn sinh','sinh@gmail.com','0971528176','Xóm nhà lá, Phường 10, Quận 11, Tp HCM')
insert into HOSOTREEM values ('Nguyễn Văn Ảnh','Nguyễn Thị na','Nguyễn Văn huy','huy@gmail.com','0978828454','Xóm nhà lá, Phường 10, Quận 11, Tp HCM')
insert into HOSOTREEM values ('Nguyễn Văn Long','Nguyễn Thị ánh','Nguyễn Văn Tèo','teo@gmail.com','0978825436','Xóm nhà lá, Phường 10, Quận 11, Tp HCM')
insert into HOSOTREEM values ('Nguyễn quốc Thịnh','Nguyễn Thị B','Nguyễn Văn Ân','an@gmail.com','0978812353','Xóm nhà lá, Phường 10, Quận 11, Tp HCM')
insert into HOSOTREEM values ('Võ Anh Dũng','Nguyễn Thị Lệ Huyền','Nguyễn Văn Nam','nam@gmail.com','0978828444','Xóm nhà Tranh, Phường 10, Quận 11, Tp HCM')
insert into HOSOTREEM values ('Nguyễn Văn Chiến','Nguyễn Thị Hường','Nguyễn Văn Cảnh','canh@gmail.com','0978823336','Xóm nhà Đất, Phường 10, Quận 11, Tp HCM')
insert into HOSOTREEM values ('Nguyễn Văn Sơn','Nguyễn Thị Huệ','Nguyễn Văn Xuân','xuan@gmail.com','0978845646','Xóm nhà lá, Phường 10, Quận 11, Tp HCM')
insert into HOSOTREEM values ('Nguyễn Văn Tú','Nguyễn Thị Lan','Nguyễn Thị Nở','no@gmail.com','0979875176','Xóm nhà lá, Phường 10, Quận 11, Tp HCM')
insert into HOSOTREEM values ('Nguyễn Văn Quốc','Nguyễn Thị Hồng','Nguyễn Văn Cao','cao@gmail.com','0978832456','Xóm nhà lá, Phường 10, Quận 11, Tp HCM')
insert into HOSOTREEM values ('Nguyễn Văn Tuấn','Nguyễn Thị Hoa','Nguyễn Văn Danh','danh@gmail.com','097432676','Xóm nhà lá, Phường 10, Quận 11, Tp HCM')
insert into HOSOTREEM values ('Nguyễn Văn Đạt','Nguyễn Thị Tuyền','Nguyễn Văn Tình','tinh@gmail.com','0978865376','Xóm nhà lá, Phường 10, Quận 11, Tp HCM')
insert into HOSOTREEM values ('Nguyễn Thành Đạt','Nguyễn Thị tuyến','Nguyễn Văn Nghiêm','nghiem@gmail.com','09733228176','Xóm nhà lá, Phường 10, Quận 11, Tp HCM')

insert into TREEM values('Nguyễn Văn Tý','Tèo','Nam','01/11/2000','Kinh','khong', 1,'Chơi một mình','Hòa đồng', 1)
insert into TREEM values('Nguyễn Văn Kha','Tý','Nam','03/30/2000','Kinh','khong', 1,'Chơi thân với nữ','Hòa đồng', 2)
insert into TREEM values('Nguyễn Văn Anh','chuột','Nam','02/11/2000','Kinh','khong', 1,'Chạy nhảy lung tung','Hòa đồng', 15)
insert into TREEM values('Nguyễn Thị Nở','bủm','Nữ','05/11/2000','Kinh','khong', 1,'Khóc dai như đĩa','Hòa đồng', 3)
insert into TREEM values('Nguyễn Thị Thanh Tuyền','trâu','Nam','01/20/2000','Kinh','khong', 1,'Chơi Thân Với Nữ','Hòa đồng', 5)
insert into TREEM values('Nguyễn Thị Ánh Tuyết','nghé','Nữ','01/22/2000','Kinh','khong', 1,'Chơi một mình','Hòa đồng', 5)
insert into TREEM values('Nguyễn Văn Nam','bin','Nam','01/19/2000','Kinh','khong', 1,'Chơi một mình','Hòa đồng', 6)
insert into TREEM values('Nguyễn Quốc Văn','nô','Nam','01/13/2000','Kinh','khong', 1,'Thích chơi trò bạo lực','Hòa đồng', 7)
insert into TREEM values('Nguyễn Quốc Việt','bu','Nam','03/03/2000','Kinh','khong', 1,'Thích sáng tạo','Hòa đồng', 8)
insert into TREEM values('Nguyễn Quốc Nam','beo','Nam','02/28/2000','Kinh','khong', 1,'Huýt sáo trong lớp','Hòa đồng', 9)
insert into TREEM values('Nguyễn Văn Tiến','gấu','Nam','01/22/2000','Kinh','khong', 1,'Chọc ghẹo bạn nữ','Hòa đồng', 10)
insert into TREEM values('Nguyễn Văn Tín','gà','Nam','07/01/2000','Kinh','khong', 1,'Nói chuyện trong lớp','Hòa đồng', 11)
insert into TREEM values('Nguyễn Văn Kha','an','Nam','07/19/2000','Kinh','khong', 1,'Đi học trể','Hòa đồng', 12)
insert into TREEM values('Nguyễn Quốc Nhã','anh','Nam','06/19/2000','Kinh','khong', 1,'Nói Chuyện Nhiều','Hòa đồng', 13)
insert into TREEM values('Nguyễn Văn Thoa','em','Nữ','05/11/2000','Kinh','khong', 1,'Chơi một mình','Hòa đồng', 14)
